/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DefaultImport } from './routes/_default'
import { Route as DashboardImport } from './routes/_dashboard'
import { Route as DefaultRegisterImport } from './routes/_default.register'
import { Route as DefaultLoginImport } from './routes/_default.login'
import { Route as DashboardOverlaysIndexImport } from './routes/_dashboard.overlays.index'
import { Route as DashboardOverlaysIdImport } from './routes/_dashboard.overlays.$id'

// Create Virtual Routes

const DefaultIndexLazyImport = createFileRoute('/_default/')()

// Create/Update Routes

const DefaultRoute = DefaultImport.update({
  id: '/_default',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRoute,
} as any)

const DefaultIndexLazyRoute = DefaultIndexLazyImport.update({
  path: '/',
  getParentRoute: () => DefaultRoute,
} as any).lazy(() =>
  import('./routes/_default.index.lazy').then((d) => d.Route),
)

const DefaultRegisterRoute = DefaultRegisterImport.update({
  path: '/register',
  getParentRoute: () => DefaultRoute,
} as any)

const DefaultLoginRoute = DefaultLoginImport.update({
  path: '/login',
  getParentRoute: () => DefaultRoute,
} as any)

const DashboardOverlaysIndexRoute = DashboardOverlaysIndexImport.update({
  path: '/overlays/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardOverlaysIdRoute = DashboardOverlaysIdImport.update({
  path: '/overlays/$id',
  getParentRoute: () => DashboardRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/_default': {
      preLoaderRoute: typeof DefaultImport
      parentRoute: typeof rootRoute
    }
    '/_default/login': {
      preLoaderRoute: typeof DefaultLoginImport
      parentRoute: typeof DefaultImport
    }
    '/_default/register': {
      preLoaderRoute: typeof DefaultRegisterImport
      parentRoute: typeof DefaultImport
    }
    '/_default/': {
      preLoaderRoute: typeof DefaultIndexLazyImport
      parentRoute: typeof DefaultImport
    }
    '/_dashboard/overlays/$id': {
      preLoaderRoute: typeof DashboardOverlaysIdImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/overlays/': {
      preLoaderRoute: typeof DashboardOverlaysIndexImport
      parentRoute: typeof DashboardImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  DashboardRoute.addChildren([
    DashboardOverlaysIdRoute,
    DashboardOverlaysIndexRoute,
  ]),
  DefaultRoute.addChildren([
    DefaultLoginRoute,
    DefaultRegisterRoute,
    DefaultIndexLazyRoute,
  ]),
])

/* prettier-ignore-end */
